#! /usr/local/bin/ruby
# -*- coding: utf-8 -*-
=begin
  rgettext - ruby version of xgettext

  Copyright (C) 2005-2009  Masao Mutoh
 
  You may redistribute it and/or modify it under the same
  license terms as Ruby.
=end

$:.unshift File::join([File::dirname($0),"..","lib"])
begin
  require 'gettext/tools/rmsgfmt'
rescue LoadError
  begin
    require 'rubygems'
    require 'gettext/tools/rmsgfmt'
  rescue LoadError
    raise 'Ruby-GetText-Package are not installed.'
  end
end

GetText.rmsgfmt
